spring:
  application:
    name: 'config-service'
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/jinho-yoo-jack/msa-config-storage
server:
  port: 8888